### ISSUE TITLE
Frontend input Image is not supported by form widgets.

### ISSUE THREAD

**Issue by ChalkyMagento** [Alekseon/magento2-widget-forms#1]
Attempting to add a form that includes image input to a CMS page. The image element does not show on the CMS page and I see this message 'Frontend input Image is not supported by form widgets.' Can you help please?

![image](https://user-images.githubusercontent.com/44672612/99795712-25ec6b00-2b24-11eb-83b2-3d5b5eab69db.png)

**Comment by marcinfr** [comment]
Thank You for Your feedback.
For now we don't support all types of fields on frontend.
Currently supported fields are:
- Text Field
- Text Area
- Select / Radio Buttons
- Checkbox

In case when other type is selected, we inform admin user about this by notification "Frontend input Image is not supported by form widgets", and fields is not renderer on frontend.

**Comment by denialdesign** [comment]
Same issue on a new install: 
Frontend input Text Field is not supported by form widgets.
Frontend input Date is not supported by form widgets.
Frontend input Text Area is not supported by form widgets.

Are any input types supported?

Magento 2.3.4

**Comment by Linek** [comment]
We are also interested

**Comment by EvasBa** [comment]
Any update on this issue?

**Comment by Linek** [comment]
Hi @EvasBa @ChalkyMagento 
We are still working on that feature. This is risky from security perspective so we're making sure that this will be fully secured. Once it's ready we'll publish that.

**Comment by Linek** [comment]
Good news @EvasBa @ChalkyMagento 

The image upload option has been just added in the latest version.

Hope you'll enjoy it.
