### ISSUE TITLE
Fields Notify Email

### ISSUE THREAD

**Issue by ticbitvax** [Alekseon/magento2-widget-forms#11]
Would there be the possibility that, in the same notification email that is sent, put the different fields with which a user has filled out the form?
Thank you very much!

**Comment by Linek** [comment]
Good idea @ticbitvax. We'll add it to the backlog.

**Comment by marcinfr** [comment]
Hello,

Its done in new version of Widget Forms.
You can get new version of extention: https://github.com/Alekseon/magento2-widget-forms/wiki/Installation-&-Updates

Thank you for getting in touch!
