### ISSUE TITLE
Magento Captcha

### ISSUE THREAD

**Issue by okanoeztuerkbasler** [Alekseon/magento2-widget-forms#12]
Hi,
In the form settings you can choose between 3 reCaptcha types.
Is it possible or do you plan to allow choosing the Magento default captcha?
(Stores > Config > Customer > Customer Config) 

Thank you and best regards.

**Comment by marcinfr** [comment]
Hi,

I have added this option in alekseon/widget-forms-re-captcha version 100.1.0.
In latest version You can select <strong>Magento Captcha</strong> as ReCaptcha Type.

You can find more about reCaptcha validation here:
[https://github.com/Alekseon/magento2-widget-forms/wiki/reCAPTCHA-Validation](url)

Please update extension to newer version. Check more informations about updating here: <br>[https://github.com/Alekseon/magento2-widget-forms/wiki/Installation-&-Updates](url)
