### ISSUE TITLE
Can't setup:upgrade after composer install

### ISSUE THREAD

**Issue by DomVit5** [Alekseon/magento2-widget-forms#15]
The problem occurs on setup:upgrade command on Magento CLI.
I am running version 2.4.1
The issue is related with  a module called "Custom Forms Email Notifications"
Error showed: "Email template '' is not defined".

**Comment by marcinfr** [comment]
Hi,
Thank You for reporting this issue.

The reason of this issue was in AlekseonEav module.
Issue is fixed in "alekseon/alekseon-eav" in version 101.1.5.

You can update this module by composer:
`composer update alekseon/alekseon-eav`
then run setup:upgrade again.
