### ISSUE TITLE
Code Quality Recommendations

### ISSUE THREAD

**Issue by lbajsarowicz** [Alekseon/magento2-widget-forms#17]
## Is your feature request related to a problem? Please describe.

The main motivation for Feature Request is to encourage Alekseon team to raise the bar of Code Quality standards, so their extension would pass Extension Review for other agencies and become well-known and recommended solution in the MageOS / Magento / Adobe Commerce ecosystem.

## Describe the solution you'd like

First and the most important, I would like Developers involved in the development of extension to acknowledge the following:

* **TG** https://developer.adobe.com/commerce/php/coding-standards/technical-guidelines/
* **EXT** https://devdocs.magento.com/guides/v2.3/ext-best-practices/bk-ext-best-practices.html
* **CP** https://devdocs.magento.com/guides/v2.3/ext-best-practices/extension-coding/common-programming-bp.html
* **CS** https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-php.html

Severity: 🔴 Major, 🟡 Minor, ⚪ Recommendation

#### 🔴 [CP] Avoid using `around` plugins at any price!

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Plugin/AddFormFieldsetWarningPlugin.php#L19

See https://developer.adobe.com/commerce/php/best-practices/extensions/#using-around-plugins

#### 🔴 Invalid HTTP code used for a response

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L94

[Invalid request is not an internal server error.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses)

#### 🔴 Use Magento `JsonHexTag` or add `JSON_HEX_TAG` to `json_encode`

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/view/frontend/templates/widget_form.phtml#L23-L24

You may be surprised, but some characters may break DOM structure and breaking out of `<script>` section. `JSON_HEX_TAG` reduces the changes for the issue to appear (see: https://www.php.net/manual/en/json.constants.php)

#### 🔴 Registry is deprecated and should not be used

https://github.com/magento/magento2/blob/9c0e1236743f5cccb13cfbf72cf1473aaebd2d9c/lib/internal/Magento/Framework/Registry.php#L14-L18

Used in:

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Model/Attribute/DefaultValueProvider/CurrentCmsPage.php#L14-L19

#### ❗ GDPR Issue: Avoid revealing if Customer is registered/subscribed!

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Observer/SubscribeToNewsletter.php#L101-L103

Replace the error message with "There was an issue while subscribing you" or something similar. The best solution is to look at the core implementation and copy the original message, this way it already covers translating it for other languages.

#### 🔴 Security vulnerability

Filter input, escape output. Make sure that all outputs are escaped correctly

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/view/frontend/templates/widget_form.phtml#L14-L17

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/view/frontend/templates/widget_form.phtml#L19

Whole https://github.com/Alekseon/magento2-widget-forms/tree/master/view/frontend/templates/form/field

#### 🟡 Replace `InstallData` and `UpgradeData` with DataPatches

* https://github.com/Alekseon/magento2-widget-forms/blob/master/Setup/InstallData.php
* https://github.com/Alekseon/magento2-widget-forms/blob/master/Setup/UpgradeData.php

When it's done, get rid of version from `module.xml`

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/etc/module.xml#L9

#### 🟡 Make sure that plugins have explicit `sortOrder`

https://github.com/Alekseon/magento2-widget-forms/blob/master/etc/adminhtml/di.xml

This way other Extension Developers can be certain how can they customize your extension behavior.

#### 🟡 [TG] 2.7. All non-public properties and methods SHOULD be private.

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L20

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L24

#### 🟡 NOTICE: Reference to the key that does not exist

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L76

Use `??` or `isset()`

#### 🟡 Use proper Exception types

Exceptions that should be displayed to the Customer should be ancestors of `LocalizedException` (look at available options, like `InvalidRequestException` etc.)

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L142-L148

#### 🟡 Redesign Controller to use `ActionInterface` instead of inheritance

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L15

#### ⚪ Code Recommendation

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L131-L134

#### ⚪ Refactor recommendation

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Model/Attribute/DefaultValueProvider/CurrentCmsPage.php#L39-L47

```php
return parent::canBeUsedForAttribute() && $this->attribute->getForm()
    && $this->attribute->getForm()->getCanUseForWidget();
```

#### ⚪ Method does never return `void`

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L59

```php
return $successTitle ?: __('Success');
```

#### ⚪ Avoid PHPDocs that do not bring any value

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L11-L14

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L38-L41

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L151-L153

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Model/Attribute/DefaultValueProvider/CurrentCmsPage.php#L21-L24

#### ⚪ Refactor recommendation

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Plugin/FromAttributeGroupCodesPlugin.php#L39-L42

```php
return $form->getCanUseForWidget() || $result;
```

#### ❔ Is there any specific reason for setting the default HTTP Response Code

https://github.com/Alekseon/magento2-widget-forms/blob/0d0a81be0cd607b99b0e6b0cb2c59ac0ea9fab30/Controller/Form/Submit.php#L86

#### ❔  Why not `<container>`?

https://github.com/Alekseon/magento2-widget-forms/blob/master/view/frontend/templates/form/additional_info.phtml

## Describe alternatives you've considered

I will try to introduce some Pull Requests with solutions in my spare time.

## Additional context

Ping me in the Issue in case of any questions.

**Comment by marcinfr** [comment]
Thank you @lbajsarowicz for such a valuable and detailed analysis. 
We will take into account Your points and work on improving code quality.

**Comment by lbajsarowicz** [comment]
@marcinfr I think that would be great to introduce ReCaptcha to your module. However, architectural recommendation is to keep it separate from the module itself (create `magento2-widget-forms-recaptcha` so you won't be coupled to any specific version of ReCaptcha.

**Comment by marcinfr** [comment]
@lbajsarowicz we have already implemented WidgetFormsReCaptcha as separated module: https://github.com/Alekseon/magento2-widget-forms-re-captcha

It supports all native magento recaptcha types:
- Magento Captcha
- reCAPTCHA v2 ("I am not a robot")
- reCAPTCHA v2 Invisible
- reCAPTCHA v3 Invisible

**Comment by lbajsarowicz** [comment]
Oh! I missed that. So cool! :-) Will review that soon.

**Comment by marcinfr** [comment]
@lbajsarowicz I have worked on all of major and minor mentioned issues. The code is updated.

I have few doubts:
- message "'This email address is already assigned to another user.'" , its the same error message as magento implemented in class Magento\Newsletter\Controller\Subscriber\NewAction, and my intention is to follow it.
- i suppose that some of non-public properties have to be protected , for example $_template to keep same visibility as magento Template block.

**Comment by lbajsarowicz** [comment]
@marcinfr Cool! Let me perform another review on Friday and get back to you.

**Comment by marcinfr** [comment]
@lbajsarowicz I'm closing this issue. Feel free to reopen it or create new one if You have any more remarks or recommendations.
