### ISSUE TITLE
Argument 'value' must be type of string, object given.

### ISSUE THREAD

**Issue by Pekkonen** [Alekseon/magento2-widget-forms#18]
Hy guys!
I have Magento 2.4.6 and I installed plugin with composer
`composer require alekseon/widget-forms 
bin/magento setup:upgrade`
Created new form with one Text field , added it to the widget and trying to submit it I've an error in 'modal-popup'
"Error filtering template: Argument 'value' must be type of string, object given."
https://www.awesomescreenshot.com/image/39832606?key=3115c51c537a8b9b2feff3dec437cf8e
Is this a common issue or do I need to debug it myself?

**Comment by marcinfr** [comment]
Hello,

Thank You for reporting issue,

Its already fixed, please run below command to update custom-forms-frontend extension to version 100.0.7: 
`composer update alekseon/custom-forms-frontend`

**Comment by Pekkonen** [comment]
Thanks!
