### ISSUE TITLE
After installation - redirect to the dashboard

### ISSUE THREAD

**Issue by yvgorshkov** [Alekseon/magento2-widget-forms#2]
After installation by:
```
composer require alekseon/widget-forms 
bin/magento setup:upgrade  
```
and clearing cache Extension doesn`t work.
Clicking on Content -> Elements -> Custom Forms just redirect administration dashboard.
Magento 2 community edition 2.2.9

How can I install this extension properly?

**Comment by marcinfr** [comment]
Hi, do You still have this problem ?

**Comment by Linek** [comment]
Ticket closed due to inactivity. Feel free @yvgorshkov to reopen if the issue still occurs.
