### ISSUE TITLE
Tabs in object function are empty and triggers JS error

### ISSUE THREAD

**Issue by SermonB** [Alekseon/magento2-widget-forms#21]
**Describe the bug**
I inserted the widget into my page but in the widget function the tabs object is empty and triggers JS errors

**Used code**
{{widget type="Alekseon\WidgetForms\Block\WidgetForm" form_id="1" hide_title="1" hide_description="1"}}

**Screenshots**
![image](https://github.com/user-attachments/assets/61c1dbda-0ce1-40ee-84f1-dbeb1433ceec)
![image](https://github.com/user-attachments/assets/410dddad-8ec0-47ee-b344-d2235d507a9e)

**Magento Version:**
Magento ver. 2.4.7-p1

**Comment by marcinfr** [comment]
Hello @SermonB , It seems that You are using hyva theme.
For now Widget Forms module is only compatible with hyva in version 102.3.*. In next versions we did some code refactoring, but hyva compatibility module was not updated for the latest widget forms module.

**Comment by marcinfr** [comment]
Hi @SermonB  
Good news! I have released a new version 1.0.16 of the compat module. 
Issue with empty tabs object is fixed.

You can update it by composer:
```
composer update hyva-themes/magento2-alekseon-widget-forms
```
It is compatible with the latest widget forms module.
Please let us know if You have any problems with the module.

**Comment by SermonB** [comment]
Thank you for the fix. The form's are displayed now.
