### ISSUE TITLE
White Page When Adding New Form

### ISSUE THREAD

**Issue by Naaaaate89** [Alekseon/magento2-widget-forms#22]
Getting a white page with links that don't work when adding custom form.

Steps to reproduce -> Content -> Manage Custom Forms -> Add New Form

![image](https://github.com/user-attachments/assets/b48a2ce5-4ac0-416b-bcb9-126547ccb519)

Running Magento ver. 2.3.1

Package operations: 5 installs, 0 updates, 0 removals
  - Installing alekseon/alekseon-eav (101.2.11): Downloading (100%)
  - Installing alekseon/widget-forms-statistics (100.0.4): Downloading (100%)     - Installing alekseon/custom-forms-builder (102.3.12): Downloading (100%)       - Installing alekseon/custom-forms-email-notification (100.1.12): Downloading (100%)
  - Installing alekseon/custom-forms-frontend (100.1.3): Downloading (100%)

**Comment by marcinfr** [comment]
Hi @Naaaaate89 
Can you check page source of a website and magento logs? Do you see any related error there?

**Comment by marcinfr** [comment]
Closed due to inactivity, If You still have issue please reopen ticket or create new one with more details.
