### ISSUE TITLE
Group in fieldsets is not working

### ISSUE THREAD

**Issue by anvanza** [Alekseon/magento2-widget-forms#25]
**Describe the bug**
The option "Group Fields In" on the form does not work as expected.
All the fields are created in a single fieldset

**To Reproduce**
1. Create a from with multiple fieldsets
2. Select "Group Fields In": "Fieldset"
3. Publish the form on the front-end

**Expected behavior**
Multiple fieldsets are used to divide the fields

**Screenshots**

**Magento Version:**
Example: Magento ver. 2.4.7-p2

**Extension versions**
alekseon/widget-forms: 102.4.2
hyva-themes/magento2-alekseon-widget-forms: 1.0.16

**Additional context**
Also using the Hyva theme, but was able to reproduce it on the demo

**Comment by marcinfr** [comment]
Hi @anvanza 

Here You can find form with grouped fields:
https://widget-forms.alekseon.com/multistep-survey.html

By configuration "Group Fields In" You can decide if You want to group fields in fieldsets or in tabs in Admin view.
You can use this groups also on frontend to have mutistep form, but You need also enable it in Widget settings -> Enable Multiple Steps

Please let me know if it helps.

**Comment by anvanza** [comment]
Hi @marcinfr , Thank you for answering this issue.
So the "Group Fields In" is mainly for the back-end and not in the front-end when Multistep is disabled?

We would like to use it in the front-end and use custom css to style certain fieldsets.

**Comment by marcinfr** [comment]
Hi @anvanza
> Hi @marcinfr , Thank you for answering this issue. So the "Group Fields In" is mainly for the back-end and not in the front-end when Multistep is disabled?
 
yes

Im closing this ticket, if you will find any other issues, please create new one.
