### ISSUE TITLE
Fail ./bin/magento setup:upgrade

### ISSUE THREAD

**Issue by yvgorshkov** [Alekseon/magento2-widget-forms#3]
After installation through
```
composer require alekseon/custom-forms-builder
```
I ran the command: ./bin/magento setup:upgrade
Then get error:
```
Impossible to process constructor argument Parameter #0 [ <required> Magento\ReCaptchaAdminUi\Model\OptionSource $recaptchaTypeSource ] of Alekseon\WidgetFormsReCaptcha\Model\Attribute\Source\ReCaptchaType class
```

How I can fix this problem?

P.S. Magento community edition 2.4.3

**Comment by marcinfr** [comment]
Hi, can You check if this class "Magento\ReCaptchaAdminUi\Model\OptionSource" exists in Your project ?

**Comment by Linek** [comment]
Ticket closed due to inactivity. Feel free @yvgorshkov to open if issue still occurs.
