### ISSUE TITLE
Magento 2.4.4

### ISSUE THREAD

**Issue by sejas76** [Alekseon/magento2-widget-forms#5]
Hello,

Just wondering if anyone has successfully run this module in the new Magento 2.4.4?
I have installed it successfully (bin/magento module:enable Alekseon_AlekseonEav Alekseon_CustomFormsBuilder Alekseon_WidgetForms Alekseon_WidgetFormsReCaptcha)  and set up the forms and widget in admin. however on load the only error message I get is on chrome console [ERROR] Failed to load the "Alekseon_WidgetForms/widget-form" template requested by "widgetForm-1".
 Any Ideas?
Thanks
Even

**Comment by ticbitvax** [comment]
The same thing happens to me, exactly the same error. Any solution?
Thanks!

**Comment by xavitriu** [comment]
We are seeing the same problem. Any idea??

**Comment by IJOL** [comment]
Hi, I'm glad to see that I'm not alone, we are experiencing the exact same issue... The form do not load in cms and the javascript console log in chrome spits the same mesage:`[ERROR] Failed to load the "Alekseon_WidgetForms/widget-form" template requested by "widgetForm-1"`

**Comment by ticbitvax** [comment]
We have been able to find the solution, or at least it has worked for us. In the "widget-form.html" file (vendor/alekseon/widget-forms/view/frontend/web/template/), change line 21 by closing the <div>

<fieldset class="fieldset">
        
            <legend class="legend">
                <span data-bind="html: title" />
            </legend>
        

        
            **<div class="field note no-label" data-bind="html: description"></div>**
        

        <fieldset class="fieldset" data-bind="html: formFieldsetHtml" />

        
        
        
    </fieldset>

@Funfelek @marcin-libelt @marcinfr @Linek 
If you could please update the file. Thank you!

**Comment by Linek** [comment]
Hi @sejas76 @ticbitvax @xavitriu @IJOL 
Thank you for your report.

We'll take care of this issue within next 5 days sprint, so please expect the update soon.

**Comment by sejas76** [comment]
Excellent, I just applied the changes, I also closed off the span tag on line 17 and the fieldset on line 25 - not sure if this makes any difference but noted that Magento 2 also kicks errors when tags are not closed correctly (found this to be the case when the pagebuilder saves img files, it saves e.g<img src="xxx" width="50px /> instead of <img src="xxx" width="50px></img>.

Just for anyone also finding issues with the newsletter settings giving errors like
TypeError: Magento\Newsletter\Model\SubscriptionManager::subscribe(): Argument #1 ($email) must be of type string, array given,
you need to ensure in Newsletter Settings "Email Field" drop down is selected for your field 'email address' or whatever you called your field containing the email address.

This is a great module, thank you for your support in maintaining this project.

**Comment by sejas76** [comment]
sorry it looks like my closing tag for img was truncated above(M2 saves <img /> instead of <img > <forwardslash img >).

**Comment by marcin-libelt** [comment]
Hello, issue has been fixed abd pushed to repo.
Thank you @sejas76 @ticbitvax for your involvement.

It seems that the most top of html elements in knockout condition tag must be a regular tag with the ending tag.
`
        <div class="field note no-label" data-bind="html: description"></div>
        `
        
This example would also work:
 `
            <legend class="legend">
                <span data-bind="html: title" />
            </legend>
        `
