### ISSUE TITLE
Option form "Notify By Email about new entities"

### ISSUE THREAD

**Issue by ticbitvax** [Alekseon/magento2-widget-forms#7]
The "Notify By Email about new entities" option does not work for us. We do not know if it is because some other option has to be activated, or if it is due to some error in the extension itself. Any help or idea about it?

**Comment by marcinfr** [comment]
Please update module "Alekseon_CustomFormsBuilder", you can do it by composer:
`composer update alekseon/custom-forms-builder`

Then You can put Your email address for notification under this configuration:
Stores -> configuration -> Alekseon Extensions -> Custom Forms -> Send Email To
