### ISSUE TITLE
Add Hyvä compatibility to readme

### ISSUE THREAD

**Issue by wigman** [Alekseon/magento2-widget-forms#8]
Perhaps you could add a note about Hyvä compatibility and link to https://gitlab.hyva.io/hyva-public/module-tracker/-/issues/236, or add the installation instructions to the readme?

**Comment by Linek** [comment]
Thanks for suggestion @wigman 

@marcin-libelt could you please take care of it?

**Comment by wigman** [comment]
Thanks for all your hard work!
